language: go
go:
  - 1.11.x

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  global:
    - GO111MODULE=on
    - DOCKER_LOGIN=crazymax
    - DOCKER_USERNAME=crazymax
    - DOCKER_REPONAME=swarm-cronjob
    - QUAY_LOGIN=crazymax
    - QUAY_USERNAME=crazymax
    - QUAY_REPONAME=swarm-cronjob
    - MICROBADGER_HOOK=https://hooks.microbadger.com/images/crazymax/swarm-cronjob/SHzfhx0g0bYSSldJP7L8cidrho8=
    - secure: Si24RzA40uuVEBf6lwjGpARSDJsw4e1SRBJRUHcTa6yw8u6aeQBloRadniua/VxPXpMKW4XXBB3wbF0NHWVDZGvD3W5AEWtZztdW6oX8Xn8w8TeoCRB+Kdie6yDLh8qSFFbkB0tQSn+RXQG/GgJ+Q/xqvg+jWHmr6djiwQyqjp3iPAO+m6SXW7UhTJOeFFZi8Ndhju1OpVxKPkaNzyrKmPUEN2D529+gAjPnMVTO+DHWbqUo7s+m1FWcTdf9xNXY33vkT/nFtbXnooa4HXPRIfreVajnaEFRg55N7DlUtcDUQyVoKrKIeqg0H3r8+yFb3PSwzrbSaOJW5YHvz4czmhD3zzQ8LcAJIxTtJ6jHg5je/bsEfPJ5LD2ZrlpelIjtiTNNvszORSYhC9Sqxwxmg8+LT1aCWqUsP6yMoCD76fDfJy5u+BrvpTdGsjGqHOskpjxgpPa+dXdpUNWL/bqyPq3UwMGTKV2fDXvX4c+EiigNZ18INCSVmzMR/X0ko4NgQYYra6YLfMlP+VnRTarrSTuj2DFqZny2OMSYZGjCOvQZxDWiEXQ82AtyGtQtTC5ALmLrLeXLARDkSF1l4UxdM5dw55Ue17h0XAkROQ76HYX5NdIe+8kjQm+7ZyNabZRgzPTIp2no0YFhZTCCioa++9roTQw8tzliFVHw0GNDzak= # DOCKER_PASSWORD
    - secure: T5YfPRSm2Z4t4ae5WVoYu/5ZQ0G1hOtuS2lmVLBrrodo4L6NoE/YMdEINa+ht1A+rpdq4u9tb7ZfM43C5kGl4D55QNWAwLADx2vtgZbyBivMRuh0br9/w/iwYO3LGmlPKykTJt6+f+vsinGKKUW66MTnbwU731JQ9OeWtV1sCf0BEEdj+iKVyuLJ49tdI01prNV3xAhp0dCo5OtQdWTrksxRx9eVUBeoeGgb0Ayb51irf5lXhHAYg5E4FurVYdo4Vzaj+qxhCdviQLyIAKDn/36+wspgagE61EITYalGPmkNbYoEPygJTr0vytnS/CeijRYdRhGby/azpoZM2MnlyBXMnkJICBYpyrzpogPl3IgwjVw4XLoNmYNffZyARtVgimLSkvEVwfuskUMLhgC1FIknmCdf8cL5TaWAzqxHDaklJ9uGSMBUmfK4z9j5bsHgmxDlNFazcZmlu0GhySVbHjbx0AQYrmN6KT9+TXn8TdNEQ75eKZBxgd5qJFPI9VXMXi9qxM5LUP3aQbnr0jvj7VnJQOYJ+gl8x6nONXuuVbad0Zr2z5aSoGxF6DI8LIAYxfK1QeAqfhrcwqRcMQVEsiWs40dVotPaKSHaZMKlHCLy46V3+cidicYLUPYvyQzmc65EMerrDDuRsqDPrSMpnqNHoWs2gLIfH0RTyCWjJ48= # QUAY_PASSWORD

before_install:
  - sudo apt-get update
  - docker --version
  - export ADVERTISE_ADDR=$(dig +short myip.opendns.com @resolver1.opendns.com)

install:
  - curl -sL https://git.io/goreleaser | head -n -2 | bash
  - tar -xf /tmp/goreleaser.tar.gz -C $GOPATH/bin
  - goreleaser -v

script: ./build.sh

deploy:
  provider: releases
  api_key:
    secure: Tu4MQ2Yt4L7Dn4MdQ3XrRVlPleFJy5PtwgTabNfpaNO/Lb5zul38xoJsUslWuPO05yAig58p3vhwfj/0mEHqDDgDkeRhLakVPXYHRfhneuw23CrTd7IVfR79tLnhO63arjAN06w8pSY09WnM2fdSUOliT8iVOsRMc7fm2x7jF+Mx3hU/mXZ1SDHddHRwO31aVSlr43ntSgfjjUFAIjCSOPnMNSovoxX51tYNZP0/9nerhaIG551W1D7kGgXoyFchThCpLU8nOKlGWAw+Xc2zNQ5FxsitH46VauLHUEHxLQixp3r565szmwfcwvle0ciF22loywOq3NH9+qjHlf0TzzFewgdlQBCp3uCVqh8m2OlruHEgtbgNkt3uqcFTN2WgQW6R2zmCD5MbDkua6EBKjNEQdDF3AgCiDOY0WIfWhYAQ62JUkE/5Sv8pM7BlyI3IzEHZqsxTM6WqSe3U1cTiSdBjWDll+WCuJrwH2UnASVcliFQ82MGCtRDOfLV3snB+H2TRMbhd18MG2/bk1RIpxjS4/epKBwHAqSt1XY8KBhIh4luoQSTfkB0NgQGsk8ZL777iotC+xLv91vdve3xqWXRdrEvtO+g9MILjjI7y+WpdN7njerzTiqgzAlzedwDc2kDWiZqBQpaz1ppMoNcPg/Qj0pqZF9mylkFK+keyRao=
  file_glob: true
  file:
    - dist/checksums.txt
    - dist/*.tar.gz
    - dist/*.zip
  skip_cleanup: true
  draft: true
  on:
    tags: true
