version: "3.2"

services:
  test:
    image: crazymax/loop
    environment:
      - DURATION=70s
    deploy:
      mode: replicated
      replicas: 0
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=0 * * * * *"
        - "swarm.cronjob.skip-running=true"
      restart_policy:
        condition: none
